### ISSUE TITLE
sorry noob question

### ISSUE THREAD

**Issue by jangshik** [Schluggi/AIOsense#113]
**Category**
- [v ] Hardware / PCB
- [ ] Software / ESPHome

**Whats your idea?**
...
691210910002 << what is this part used for?
I am trying to build the sensor with these components.

ESP32-C3 mini (PCB)
BME280(PCB)
HLK-LD2410C (PCB)
GY-302-BH1750 (PCB)
im going to skip pir sensor, and i  am in middle of ordering other parts. i was wondering what 691210910002 terminal block 2pos is intended for.

Thank you in advance.

**Comment by jangshik** [comment]
![image](https://github.com/Schluggi/AIOsense/assets/29394539/8d89c7a5-c98a-4c70-8fe9-7b2636df56db)
im guessing its for this place, but is it required for esp32 c3 mini lolin?

**Comment by Schluggi** [comment]
Hi,

the terminal block is optional to power up the board. It fits under the C3 mini but you can also power the board the via USB-C connector of the C3.

Does this answer your question? :)

**Comment by jangshik** [comment]
thank you it solved my big question. 
i made the order from AIOsense-v2.1.0.zip file so i think i should be fine.
thank you for this great project!
