### ISSUE TITLE
simple question about ld2410

### ISSUE THREAD

**Issue by jangshik** [Schluggi/AIOsense#117]
**Category**
- [ ] Hardware / PCB
- [x] Software / ESPHome

**Whats your idea?**
...
it seems that in ld2410 yaml, a substitution is declared for
  ld2410_max_distance_move: 4.5m
  ld2410_max_distance_still: 4.5m
but can not find anywhere it is used for. can i change this value to change the detection range?

**Comment by Schluggi** [comment]
Hi,

interesting. I've never noticed. I just removed the substitution and bump the configuration to the latest version (#118).

You can (now) configure ld2410_max_distance_move & ld2410_max_distance_still via HomeAssistant:
![image](https://github.com/Schluggi/AIOsense/assets/43608073/10a14d95-f5cb-42e4-b23b-13d2db919a80)

You may have to update your the LD2410 firmware first to be capable to use all features: https://www.youtube.com/watch?v=t8-JdVVVH34
