### ISSUE TITLE
change to ESPHome integrated sen0935 feature

### ISSUE THREAD

**Issue by florianmulatz** [Schluggi/AIOsense#125]
**Category**
- [ ] Hardware / PCB
- [X] Software / ESPHome

**What would you like to improve?**
I would suggest to use the "own" integrated ESPHome feature for driving the sen0395 sensor so no specific effort is needed to take care on an own integration.

[Changelog](https://github.com/esphome/esphome/releases/tag/2023.11.0)

Cheers

**Comment by Schluggi** [comment]
Hi @florianmulatz, thank you for noticing. I just replaced it. Feel free to give feedback in #123.

**Comment by florianmulatz** [comment]
> Hi @florianmulatz, thank you for noticing. I just replaced it. Feel free to give feedback in #123.

Working perfectly! - Automatically created configuration for 3 individual segments.
