### ISSUE TITLE
Set Temperature Offset according to CPU-temperature

### ISSUE THREAD

**Issue by florianmulatz** [Schluggi/AIOsense#128]
**Category**
- [ ] Hardware / PCB
- [X] Software / ESPHome

Just an idea --> 

I don't have the skills to do the necessary calculations, but I think since the BME sensor's temperature reading is in direct correlation to the ESP's CPU temperature, it should be mathematically possible to calculate the offset automatically.

Cheers

**Comment by Schluggi** [comment]
Hi @florianmulatz,

Great idea but not really realizable. The other modules especially the mmwave increase the temperature as well and you do not haveto plug in all modules. Thats to many variables you can change. So thank you for the suggestion but for now this is not realizable.
