### ISSUE TITLE
Evaluate Speaker

### ISSUE THREAD

**Issue by Schluggi** [Schluggi/AIOsense#129]
We need a speaker for a better voice assistant experience.
Is issue is about finding a good one that does not suck and is affordable.
It has to work with MAX98357A amplifier.

### [3013](https://www.aliexpress.com/item/1005005246154058.html)
- (+) Very cheap (<1$)
- (+) Sounds surprisingly well
- (-) Is THT, so no easy plug & play in case of a board upgrade

**Comment by mourix** [comment]
I've tested the 3013, and compared it to the [2307](https://www.aliexpress.com/item/1005005246154058.html). Both sound surprisingly well. They have some resonance and low bass but are very comparable to affordable smartphones. The M5Stack Atom Echo sounds much worse.
