### ISSUE TITLE
Evaluate Microphone

### ISSUE THREAD

**Issue by Schluggi** [Schluggi/AIOsense#131]
Is issue is about finding a good microphone that does not suck and is affordable.
It has to be an I²S microphone

### [INMP441](https://de.aliexpress.com/item/32962426410.html)
- (+) Already supported
- (+) Works well
- (+) Recommendation from HA
- (-) The legit TDK INMP441 part seems to be EOL, so it is very unclear as to the origin of these mics.

### [SPM1423](https://shop.m5stack.com/products/pdm-microphone-unit-spm1423?ref=NabuCasa)
- (wip)
- (+) Recommendation from HA
- (-) Pre-Cased and a bit bulky

**Comment by mourix** [comment]
I obtained the ATOM Echo which integrates the SPM1423. and compared it to the INMP441. In my breadboard testing, I have found no significant differences between the two. Both have a similar success rate when looking at the speech to text result in the ESPhome logs.

A new contender is the [Sipeed I2S Mic Module](https://www.seeedstudio.com/Sipeed-I2S-Mic-for-MAIX-Dev-Boards-p-2887.html):

- (+) Smaller size compared to other sensors
- (+) Similar quality to other sensors
- (+) Widely available
- (-) Variations on Aliexpress swap the VCC and GND pins. So people will have to be careful when ordering.
