### ISSUE TITLE
wrong labes for J1

### ISSUE THREAD

**Issue by baerrs** [Schluggi/AIOsense#17]
I'm new to this project, but I believe the labels need to be corrected for J1 on v2.0 (maybe v1 as well, I didn't check).
![image](https://user-images.githubusercontent.com/56986668/211430995-9fe8bef4-c40c-4f30-be6c-d9983fe91084.png)

**Comment by Schluggi** [comment]
Thank you for reporting. I'm sure, you're right. I'll fix it.
