### ISSUE TITLE
ESPHome 2024.2.0 change to BME280 

### ISSUE THREAD

**Issue by sarreck** [Schluggi/AIOsense#179]
**Category**
- [ ] Hardware / PCB
- [ X] Software / ESPHome

**Version of ESPHome / AIOsense**
Latest

**Describe the bug**
The latest release of ESPHome "ESPHome 2024.2.0" has a breaking change in the BME280 component. 

I believe that the esphome/packages/sensors/bme280.yaml file needs to be updated as advised below. 

From the docs:

_Breaking change notes: The original bme280 component has been renamed to bme280_i2c for consistency with other platforms. To update your configuration, simply replace bme280 with bme280_i2c. No other changes are required.__

https://github.com/esphome/esphome/pull/5538

**Comment by Schluggi** [comment]
Thank you for noticing.

Fixed in the latest release by #180:
https://github.com/Schluggi/AIOsense/releases/tag/esphome-v3.0.1
