### ISSUE TITLE
Request for enhancement (RFE): Redesign the 5V Power Input

### ISSUE THREAD

**Issue by florianmulatz** [Schluggi/AIOsense#18]
Hi Schluggi,

I suggest to redesign the power input to not use a "Male PIN-Header" but a "wire-to-board-terminal-block" like this one --> [WUERTH Terminal-block](https://at.farnell.com/wurth-elektronik/691216410002/reihenklemme-wtb-2way-30-12awg/dp/3768503)

At least on the ESP32, the USB port is on the top. I'm not sure if the ESP8266 has it on the bottom, like your 3D model. Since you won't be supporting the 8266 anymore anyway, it would at least be worth considering, because with a terminal block you might have more strain relief

![23-01-19 15-35-17 2106](https://user-images.githubusercontent.com/33655308/213471071-eab55e73-4265-4036-9204-da07bf19ac22.jpg)

Cheers Flo

**Comment by Schluggi** [comment]
@florianmulatz, thank you for your input. I'll keep this in mind before the final v2 release. It is something we can quickly change. 👍

**Comment by Schluggi** [comment]
I just tested the tolerances with my v2.0-rc2 board with an ESP8266. Its really tight! 😄 
So maybe we can move the IO-ports under the ESP and the power connector to the IO-panel. We'll see :)

**Comment by florianmulatz** [comment]
Does the "tightness" makes it not good? I think there will be terminal-blocks with even a smaller "housing" at least this one was something I had at home. Just for reference (it has a height of 9,95mm) - I don't know the exact manufacturer of this one - since I bought it very cheap on AliExpress.

The one from Farnell above is wrong - I did not take care on the pitch. This one should fit better --> [WUERTH Terminal-Block](https://www.digikey.at/de/products/detail/w%C3%BCrth-elektronik/691210910002/10668428). It has a height of only 8,5mm

Cheers

**Comment by Schluggi** [comment]
8,5mm sounds great. I changed it :)


![image](https://user-images.githubusercontent.com/43608073/213887607-357339b7-ee04-4c80-9f10-b8536b4d8c43.png)

**Comment by florianmulatz** [comment]
Thx for your fast update! - Issue closed
