### ISSUE TITLE
Issues with mmwave GPIO pin

### ISSUE THREAD

**Issue by MeisterGig** [Schluggi/AIOsense#23]
I am currently having issues with the mmwave GPIO pin on the ESP32-S2. Sometimes when the pin i high, it isn't detected by the ESP. I checked the connection, which seems to be okay. Maybe the issue is the internal pulldown.

Anyways I was searching for other solutions. I found out that the mmwave sensor is also sending the value over UART so i tried to write a custom binary sensor component for that, but haven't gotten far due to my horrible C skills.

But i now also found that someone else might have already done the work:  https://github.com/esphome/esphome/pull/4203

We could evaluate this solution and maybe save a gpio pin, which can then be used for something else, like audio output.

**Comment by Schluggi** [comment]
Does the any other ESP work for you?

**Comment by Schluggi** [comment]
@MeisterGig any update? Otherwise I would close this issue.

**Comment by MeisterGig** [comment]
I haven't tried it anymore.

**Comment by Schluggi** [comment]
I'll close the issue. You can reopen it in case of new information.
