### ISSUE TITLE
Add support for HLK-LD2410C

### ISSUE THREAD

**Issue by koloodziej** [Schluggi/AIOsense#33]
There is a new version of LD2410 called LD2410C link: https://de.aliexpress.com/item/1005005047841163.html

It has 0.1" pins so it could be easier to mount/solder. Can you make make PCB for that?

**Comment by Schluggi** [comment]
I'll add this soon but I've one question: 
Does the ESPHome component for the LD2410 work with the LD2410C? Have you tested this?

https://esphome.io/components/sensor/ld2410.html?highlight=ld2410

**Comment by regevbr** [comment]
Works indeed
