### ISSUE TITLE
PIR / SEN0395 does not fit together

### ISSUE THREAD

**Issue by florianmulatz** [Schluggi/AIOsense#53]
**Category**
- [X] Hardware / PCB
- [ ] Software / ESPHome

**v2 - RC4**
...

It looks like that the PIR does not fix together with SEN0395 (at least when mounted via "socket")
Did you guys managed to get this together?
...
![23-03-22 09-47-06 2326](https://user-images.githubusercontent.com/33655308/226849736-04ce2ad6-5265-49fa-bb27-8961e31b4f1d.jpg)

![23-03-22 09-47-07 2327](https://user-images.githubusercontent.com/33655308/226849761-8bf4a1dc-070c-479f-90aa-c9ec62ec794b.jpg)

![23-03-22 09-52-55 2328](https://user-images.githubusercontent.com/33655308/226850288-e9e9646e-3be1-41bd-97f8-30f5b21b76f3.jpg)

**Comment by Schluggi** [comment]
Hi @florianmulatz,

you need a TO-5 3-pin socket: [Mouser](https://www.mouser.de/ProductDetail/Mill-Max/917-43-103-41-005000?qs=teNCaa%2FZ3auQVxVMs%2F5ihg%3D%3D), [Digi-Key](https://www.digikey.com/en/products/detail/mill-max-manufacturing-corp/917-43-103-41-005000/1212170?s=N4IgTCBcDaIJwEYDsBaALAZhQgDFtCKOOArMTiALoC%2BQA)

This is noticed in the docs [here](https://aiosense.readthedocs.io/en/latest/sensors/#motion-sensor-pir).

**Comment by florianmulatz** [comment]
ok thx - didn't notice that!

**Comment by florianmulatz** [comment]
I found those sockets too expensive to be honest  so I cheated :) 
It's not "beautiful" but it works and when it's in it's case afterwards nobody would recognize :)

Cheers
![23-03-22 12-33-04 2329](https://user-images.githubusercontent.com/33655308/226892154-d3199dcf-7b47-4e6d-be7c-4a500473afac.jpg)
