### ISSUE TITLE
Generic i2c pin orientation

### ISSUE THREAD

**Issue by cadriel** [Schluggi/AIOsense#55]
**Category**
- [*] Hardware / PCB

**Version of ESPHome / AIOsense**
2.0 RC4

**Describe the bug**
The PCB sensor pin orientation forces the sensor boards to be mounted upside down. This means the sensor chips themselves end up facing down / toward the PCB - rather than up.  Secondarily, it means the pins on the sensor boards need to be soldered in an uncommon way (upside down..) which in turn means soldering is a bit more difficult.

This runs true with the sensor boards linked in the documentation.

Would it make more sense to have these pin holes swapped around?

![IMG_1834](https://user-images.githubusercontent.com/205520/228068772-de31e4cf-cd67-4aca-857c-d723e157526c.jpeg)

Image above represents the same sensor board with pins soldered each way to help illustrate the problem. The top sensor board is how you would normally solder the pins, however - this causes the board to extend outside of the main PCB. The bottom sensor board is pinned in reverse in order to have it oriented correctly.

**Comment by Schluggi** [comment]
> Would it make more sense to have these pin holes swapped around?

Absolutely! I'll change it in v2.1.0.
