### ISSUE TITLE
Add speaker to support voice assist 

### ISSUE THREAD

**Issue by regevbr** [Schluggi/AIOsense#74]
**Category**
- [x] Hardware / PCB
- [ ] Software / ESPHome

**Whats your idea?**

Now that i2s microphones are supported (starting 2023.5) and the new assist functionality that comes with it, this project became even more awesome! But it ia missing one thing - the ability to hear the response. Can you add support for a speaker as well? 
...

**Comment by lukas-holzner** [comment]
It would be interesting if the ESP-32 C3 is even able to drive all of these devices especially microphone and speakers need a lot of RAM according to the esp home website https://esphome.io/components/speaker/i2s_audio
There are also other alternatives [MAX98357A Amazon.de](https://www.amazon.de/dp/B09PL947ZG) [MAX98357 Aliexpress](https://www.aliexpress.com/item/33043664469.html) in mono.

I mean stereo would be nice, but how good is the audio quality over a ESP I2S Bus ? Would it be usable for an audio system? (Streaming Music)

BTW here is the same board from adafruit, but cheaper https://www.aliexpress.com/item/1005005698015422.html
